name: Deploy

on:
  # Trigger the workflow on push on main branch,
  push:
    branches:
      - main
      
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repos & submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build & deploy with Pelican
      uses: timlehr/gh-pages-pelican-action@master
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        GH_PAGES_CNAME: ${{secrets.DOMAIN_CNAME}}
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: output # The folder the action should deploy.
