name: Deploy

on:
  # Trigger the workflow on push on main branch,
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repos & submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Extend PATH
      run: export PATH="$PATH:$GITHUB_WORKSPACE/pneumatic/node_modules/.bin"
    - name: Build & deploy with Pelican
      uses: justgoodin/pelican-to-github-pages@v1.0.2
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        GH_PAGES_CNAME: ${{secrets.DOMAIN_CNAME}}
        PELICAN_THEME_FOLDER: pneumatic